### ISSUE TITLE
AttributeError: Not an Aho-Corasick automaton yet

### ISSUE THREAD

**Issue by rgaiacs** [yuvipanda/cryptnono#8]
Hi @yuvipanda,

I'm getting

```
Exception ignored on calling ctypes callback function: <function RingBuf.open_ring_buffer.<locals>.ringbuf_cb_ at 0x7f5affafbba0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/table.py", line 1260, in ringbuf_cb_
    ret = callback(ctx, data, size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/execwhacker.py", line 131, in process_event
    kill_if_needed(
  File "/scripts/execwhacker.py", line 36, in kill_if_needed
    for _, b in banned_strings_automaton.iter(cmdline):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
```

in the log of the cryptnono pod. Can you help me?

**Comment by yuvipanda** [comment]
@rgaiacs hmm, that's very weird! What is the image tag that's running?

**Comment by rgaiacs** [comment]
@yuvipanda The Docker image tag is `quay.io/yuvipanda/cryptnono:v0.2.1`.

Description of the pod:

```
Name:             binderhub-cryptnono-kn4zm
Namespace:        gesis
Priority:         0
Service Account:  default
Node:             spko-css-app03/194.95.75.12
Start Time:       Thu, 02 Nov 2023 07:38:13 +0100
Labels:           app.kubernetes.io/instance=binderhub
                  app.kubernetes.io/name=cryptnono
                  controller-revision-hash=6c9d45476
                  pod-template-generation=5
Annotations:      checksum/config: 85e86eb6d204d571c0ac4f1008b5f93559dc11dee1781a0488a0ceef40a184bf
                  cni.projectcalico.org/containerID: c799a744aedd70067dcef1aae4dbc1248c5a0aa6df80f9c947364a9e9516a5e0
                  cni.projectcalico.org/podIP: 10.244.95.146/32
                  cni.projectcalico.org/podIPs: 10.244.95.146/32
Status:           Running
IP:               10.244.95.146
IPs:
  IP:           10.244.95.146
Controlled By:  DaemonSet/binderhub-cryptnono
Init Containers:
  fetch-kernel-headers:
    Container ID:   containerd://74650459c0e4d86210d199c7c75b93a4c9d7c48e047ac06c6cee01412f259844
    Image:          quay.io/yuvipanda/fetch-kernel-headers:v0.2.1
    Image ID:       quay.io/yuvipanda/fetch-kernel-headers@sha256:6e0603c384ff25c7baedca8f3d3bcad4d0bd76f6388e1028a2f54f42741fd7e7
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 02 Nov 2023 07:39:04 +0100
      Finished:     Thu, 02 Nov 2023 07:39:04 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /boot.host from boot-host (rw)
      /etc/lsb-release.host from lsb-release (ro)
      /etc/os-release.host from os-release (ro)
      /lib/modules from modules-dir (rw)
      /usr/src/ from linux-headers-generated (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4ngnc (ro)
Containers:
  execwhacker:
    Container ID:  containerd://0e5a9d4b4435f84827708de31793d24a56148d29a002f758ea8b50dfe9ab6c98
    Image:         quay.io/yuvipanda/cryptnono:v0.2.1
    Image ID:      quay.io/yuvipanda/cryptnono@sha256:394de0b693b43bb347d4c402239c70bba69288fe4cfdf1aaab0687d28ccf354f
    Port:          <none>
    Host Port:     <none>
    Args:
      /scripts/execwhacker.py
    State:          Running
      Started:      Thu, 02 Nov 2023 07:39:24 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /config from config (ro)
      /lib/modules from modules-dir (ro)
      /sys from sys (ro)
      /usr/src/ from linux-headers-generated (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4ngnc (ro)
  monero:
    Container ID:  containerd://cb708c829a7607140ae3970c19cf1cc68491f95530e7e85e7da14df93b38949d
    Image:         quay.io/yuvipanda/cryptnono:v0.2.1
    Image ID:      quay.io/yuvipanda/cryptnono@sha256:394de0b693b43bb347d4c402239c70bba69288fe4cfdf1aaab0687d28ccf354f
    Port:          <none>
    Host Port:     <none>
    Args:
      /scripts/monero.bt
    State:          Running
      Started:      Thu, 02 Nov 2023 07:39:24 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /lib/modules from modules-dir (ro)
      /lib/modules.host from modules-host (ro)
      /sys from sys (ro)
      /usr/src/ from linux-headers-generated (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4ngnc (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      binderhub-cryptnono
    Optional:  false
  usr-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr
    HostPathType:
  modules-host:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
  lsb-release:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/lsb-release
    HostPathType:
  os-release:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:
  modules-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/cryptnono/linux-headers/modules_dir
    HostPathType:
  linux-headers-generated:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/cryptnono/linux-headers/generated
    HostPathType:
  boot-host:
    Type:          HostPath (bare host directory volume)
    Path:          /boot
    HostPathType:
  kube-api-access-4ngnc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 hub.jupyter.org/dedicated=user:NoSchedule
                             hub.jupyter.org_dedicated=user:NoSchedule
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:                      <none>
```

**Comment by yuvipanda** [comment]
@rgaiacs hmm, strange. if you delete the pod and it restarts, is the error still there?

**Comment by rgaiacs** [comment]
Delete the pods has **no** effect. Same error.

**Comment by yuvipanda** [comment]
hmm, let me push a temp image and see if that fixes it.

**Comment by rgaiacs** [comment]
Same errror.

```
2023-11-08 12:14:32,789 Found 0 substrings to check process cmdlines for
2023-11-08 12:14:32,789 Found 0 patterns to explicitly allow
2023-11-08 12:14:32,789 Compiling and loading BPF program...
2023-11-08 12:14:34,211 Took 1.43s to startup
2023-11-08 12:14:34,212 Watching for processes we don't like...
Exception ignored on calling ctypes callback function: <function RingBuf.open_ring_buffer.<locals>.ringbuf_cb_ at 0x7f99ebf37ba0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/table.py", line 1260, in ringbuf_cb_
    ret = callback(ctx, data, size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/execwhacker.py", line 78, in process_event
    kill_if_needed(banned_strings_automaton, allowed_patterns, cmdline, event.pid)
  File "/scripts/execwhacker.py", line 37, in kill_if_needed
    for _, b in banned_strings_automaton.iter(cmdline):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
```

**Comment by yuvipanda** [comment]
@rgaiacs AHA! I think I see the problem!

See the first few lines - it has found 0 patterns! It looks like the secret config from mybinder.org-deploy is not being passed through here?

**Comment by rgaiacs** [comment]
Thanks @yuvipanda for find the issue. Things looks good now:

```
2023-11-08 14:29:49,177 Found NNN substrings to check process cmdlines for
2023-11-08 14:29:49,177 Found NNN patterns to explicitly allow
2023-11-08 14:29:49,177 Compiling and loading BPF program...
2023-11-08 14:29:53,371 Took 4.25s to startup
2023-11-08 14:29:53,371 Watching for processes we don't like...
```

where `NNN` > 0.

**Comment by yuvipanda** [comment]
@rgaiacs I've now added a 'warning' that looks like this:

```
2023-11-08 14:47:23,482 WARNING: No substrings to whack have been specified, so execwhacker is useless! Check your config?
```
